package io

// 244 client→server opcodes. Java: jagex2.io.Protocol + Client-TS src/io/ClientProt.ts.
// Written RAW through Packet.P1Isaac (opcode + ISAAC keystream). Java's
// CLIENTPROT_LOOKUP table is a deobfuscation artifact (never read at runtime by
// Java or TS) — intentionally not ported.
const (
	CLIENTPROT_NO_TIMEOUT            = 107
	CLIENTPROT_IDLE_TIMER            = 146
	CLIENTPROT_EVENT_TRACKING        = 217
	CLIENTPROT_ANTICHEAT_OPLOGIC1    = 47
	CLIENTPROT_ANTICHEAT_OPLOGIC2    = 218
	CLIENTPROT_ANTICHEAT_OPLOGIC3    = 37
	CLIENTPROT_ANTICHEAT_OPLOGIC4    = 34
	CLIENTPROT_ANTICHEAT_OPLOGIC5    = 7
	CLIENTPROT_ANTICHEAT_OPLOGIC6    = 177
	CLIENTPROT_ANTICHEAT_OPLOGIC7    = 50
	CLIENTPROT_ANTICHEAT_OPLOGIC8    = 100
	CLIENTPROT_ANTICHEAT_OPLOGIC9    = 169
	CLIENTPROT_ANTICHEAT_CYCLELOGIC1 = 46
	CLIENTPROT_ANTICHEAT_CYCLELOGIC2 = 148
	CLIENTPROT_ANTICHEAT_CYCLELOGIC3 = 144
	CLIENTPROT_ANTICHEAT_CYCLELOGIC4 = 41
	CLIENTPROT_ANTICHEAT_CYCLELOGIC5 = 232
	CLIENTPROT_ANTICHEAT_CYCLELOGIC6 = 215
	CLIENTPROT_OPOBJ1                = 231
	CLIENTPROT_OPOBJ2                = 110
	CLIENTPROT_OPOBJ3                = 27
	CLIENTPROT_OPOBJ4                = 17
	CLIENTPROT_OPOBJ5                = 225
	CLIENTPROT_OPOBJT                = 25
	CLIENTPROT_OPOBJU                = 111
	CLIENTPROT_OPNPC1                = 222
	CLIENTPROT_OPNPC2                = 84
	CLIENTPROT_OPNPC3                = 132
	CLIENTPROT_OPNPC4                = 229
	CLIENTPROT_OPNPC5                = 102
	CLIENTPROT_OPNPCT                = 101
	CLIENTPROT_OPNPCU                = 52
	CLIENTPROT_OPLOC1                = 238
	CLIENTPROT_OPLOC2                = 38
	CLIENTPROT_OPLOC3                = 19
	CLIENTPROT_OPLOC4                = 55
	CLIENTPROT_OPLOC5                = 243
	CLIENTPROT_OPLOCT                = 182
	CLIENTPROT_OPLOCU                = 106
	CLIENTPROT_OPPLAYER1             = 211
	CLIENTPROT_OPPLAYER2             = 219
	CLIENTPROT_OPPLAYER3             = 64
	CLIENTPROT_OPPLAYER4             = 43
	CLIENTPROT_OPPLAYERT             = 73
	CLIENTPROT_OPPLAYERU             = 48
	CLIENTPROT_OPHELD1               = 228
	CLIENTPROT_OPHELD2               = 166
	CLIENTPROT_OPHELD3               = 221
	CLIENTPROT_OPHELD4               = 6
	CLIENTPROT_OPHELD5               = 133
	CLIENTPROT_OPHELDT               = 143
	CLIENTPROT_OPHELDU               = 58
	CLIENTPROT_INV_BUTTON1           = 153
	CLIENTPROT_INV_BUTTON2           = 193
	CLIENTPROT_INV_BUTTON3           = 158
	CLIENTPROT_INV_BUTTON4           = 204
	CLIENTPROT_INV_BUTTON5           = 212
	CLIENTPROT_IF_BUTTON             = 39
	CLIENTPROT_RESUME_PAUSEBUTTON    = 11
	CLIENTPROT_CLOSE_MODAL           = 187
	CLIENTPROT_RESUME_P_COUNTDIALOG  = 190
	CLIENTPROT_TUTORIAL_CLICKSIDE    = 233
	CLIENTPROT_MOVE_OPCLICK          = 167
	CLIENTPROT_REPORT_ABUSE          = 251
	CLIENTPROT_MOVE_MINIMAPCLICK     = 56
	CLIENTPROT_INV_BUTTOND           = 81
	CLIENTPROT_IGNORELIST_DEL        = 207
	CLIENTPROT_IGNORELIST_ADD        = 203
	CLIENTPROT_IF_PLAYERDESIGN       = 8
	CLIENTPROT_CHAT_SETMODE          = 98
	CLIENTPROT_MESSAGE_PRIVATE       = 170
	CLIENTPROT_FRIENDLIST_DEL        = 69
	CLIENTPROT_FRIENDLIST_ADD        = 9
	CLIENTPROT_CLIENT_CHEAT          = 76
	CLIENTPROT_MESSAGE_PUBLIC        = 171
	CLIENTPROT_MOVE_GAMECLICK        = 63
)
