package client

// 245.2 client→server opcodes. Numbers: Client.java pIsaac/interactWithLoc
// sites @176a85f; names: the deob's adjacent // LABEL comments (verified
// against the 244 set — every label pairs 1:1, values renumbered per build).
// Written RAW through Packet.P1Isaac (opcode + ISAAC keystream). Java's
// CLIENTPROT_LOOKUP table is a deobfuscation artifact (never read at runtime
// by Java 244 or 245.2, nor TS) — intentionally not ported.
const (
	CLIENTPROT_NO_TIMEOUT            = 206
	CLIENTPROT_IDLE_TIMER            = 102
	CLIENTPROT_EVENT_TRACKING        = 19
	CLIENTPROT_ANTICHEAT_OPLOGIC1    = 87
	CLIENTPROT_ANTICHEAT_OPLOGIC2    = 95
	CLIENTPROT_ANTICHEAT_OPLOGIC3    = 146
	CLIENTPROT_ANTICHEAT_OPLOGIC4    = 186
	CLIENTPROT_ANTICHEAT_OPLOGIC5    = 74
	CLIENTPROT_ANTICHEAT_OPLOGIC6    = 250
	CLIENTPROT_ANTICHEAT_OPLOGIC7    = 119
	CLIENTPROT_ANTICHEAT_OPLOGIC8    = 171
	CLIENTPROT_ANTICHEAT_OPLOGIC9    = 233
	CLIENTPROT_ANTICHEAT_CYCLELOGIC1 = 136
	CLIENTPROT_ANTICHEAT_CYCLELOGIC2 = 223
	CLIENTPROT_ANTICHEAT_CYCLELOGIC3 = 181
	CLIENTPROT_ANTICHEAT_CYCLELOGIC4 = 94
	CLIENTPROT_ANTICHEAT_CYCLELOGIC5 = 63
	CLIENTPROT_ANTICHEAT_CYCLELOGIC6 = 112
	CLIENTPROT_OPOBJ1                = 113
	CLIENTPROT_OPOBJ2                = 238
	CLIENTPROT_OPOBJ3                = 55
	CLIENTPROT_OPOBJ4                = 17
	CLIENTPROT_OPOBJ5                = 247
	CLIENTPROT_OPOBJT                = 122
	CLIENTPROT_OPOBJU                = 143
	CLIENTPROT_OPNPC1                = 180
	CLIENTPROT_OPNPC2                = 252
	CLIENTPROT_OPNPC3                = 196
	CLIENTPROT_OPNPC4                = 107
	CLIENTPROT_OPNPC5                = 43
	CLIENTPROT_OPNPCT                = 141
	CLIENTPROT_OPNPCU                = 14
	CLIENTPROT_OPLOC1                = 1
	CLIENTPROT_OPLOC2                = 219
	CLIENTPROT_OPLOC3                = 226
	CLIENTPROT_OPLOC4                = 204
	CLIENTPROT_OPLOC5                = 86
	CLIENTPROT_OPLOCT                = 208
	CLIENTPROT_OPLOCU                = 147
	CLIENTPROT_OPPLAYER1             = 135
	CLIENTPROT_OPPLAYER2             = 165
	CLIENTPROT_OPPLAYER3             = 172
	CLIENTPROT_OPPLAYER4             = 54
	CLIENTPROT_OPPLAYERT             = 52
	CLIENTPROT_OPPLAYERU             = 210
	CLIENTPROT_OPHELD1               = 104
	CLIENTPROT_OPHELD2               = 193
	CLIENTPROT_OPHELD3               = 115
	CLIENTPROT_OPHELD4               = 194
	CLIENTPROT_OPHELD5               = 9
	CLIENTPROT_OPHELDT               = 188
	CLIENTPROT_OPHELDU               = 126
	CLIENTPROT_INV_BUTTON1           = 13
	CLIENTPROT_INV_BUTTON2           = 58
	CLIENTPROT_INV_BUTTON3           = 48
	CLIENTPROT_INV_BUTTON4           = 183
	CLIENTPROT_INV_BUTTON5           = 242
	CLIENTPROT_IF_BUTTON             = 177
	CLIENTPROT_RESUME_PAUSEBUTTON    = 239
	CLIENTPROT_CLOSE_MODAL           = 245
	CLIENTPROT_RESUME_P_COUNTDIALOG  = 241
	CLIENTPROT_TUTORIAL_CLICKSIDE    = 243
	CLIENTPROT_MOVE_OPCLICK          = 216
	CLIENTPROT_REPORT_ABUSE          = 205
	CLIENTPROT_MOVE_MINIMAPCLICK     = 198
	CLIENTPROT_INV_BUTTOND           = 7
	CLIENTPROT_IGNORELIST_DEL        = 4
	CLIENTPROT_IGNORELIST_ADD        = 20
	CLIENTPROT_IF_PLAYERDESIGN       = 150
	CLIENTPROT_CHAT_SETMODE          = 8
	CLIENTPROT_MESSAGE_PRIVATE       = 99
	CLIENTPROT_FRIENDLIST_DEL        = 61
	CLIENTPROT_FRIENDLIST_ADD        = 116
	CLIENTPROT_CLIENT_CHEAT          = 11
	CLIENTPROT_MESSAGE_PUBLIC        = 78
	CLIENTPROT_MOVE_GAMECLICK        = 182
)
